# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equalizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
import images
from EqualizerBackend import Equalizer
import sys
import os
from os import path
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1416, 929)
        app.setWindowIcon(QtGui.QIcon("Icons/equalizerLogo.png"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.SignalsVLayout = QtWidgets.QVBoxLayout()
        self.SignalsVLayout.setObjectName("SignalsVLayout")
        self.inputHLayout = QtWidgets.QHBoxLayout()
        self.inputHLayout.setObjectName("inputHLayout")
        self.input_signal_graph = PlotWidget(self.tab)
        self.input_signal_graph.setMinimumSize(QtCore.QSize(660, 200))
        self.input_signal_graph.setMaximumSize(QtCore.QSize(5000, 220))
        self.input_signal_graph.setLabel("bottom", text="Time(sec)")
        self.input_signal_graph.setLabel("left", text="Amplitude")
        self.input_signal_graph.setObjectName("input_signal_graph")
        self.inputHLayout.addWidget(self.input_signal_graph)
        self.input_spectro = QtWidgets.QFrame(self.tab)
        self.input_spectro.setMinimumSize(QtCore.QSize(660, 220))
        self.input_spectro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_spectro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_spectro.setObjectName("input_spectro")

        # create a horizontal layout
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout(self.input_spectro)
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        ##Canvas Here
        self.figure = plt.figure()
        self.canvas = FigureCanvas(self.figure)
        ##End Of Canvas
        ##Add Canvas
        self.horizontalLayout_58.addWidget(self.canvas)
        # end of horizontal layout

        self.inputHLayout.addWidget(self.input_spectro)
        self.SignalsVLayout.addLayout(self.inputHLayout)
        self.hide_input_spectro_checkbox = QtWidgets.QCheckBox(self.tab)
        self.hide_input_spectro_checkbox.setObjectName("hide_input_spectro_checkbox")
        self.SignalsVLayout.addWidget(self.hide_input_spectro_checkbox)
        self.outputHLayout = QtWidgets.QHBoxLayout()
        self.outputHLayout.setObjectName("outputHLayout")
        self.output_signal_graph = PlotWidget(self.tab)
        self.output_signal_graph.setMinimumSize(QtCore.QSize(660, 200))
        self.output_signal_graph.setMaximumSize(QtCore.QSize(5000, 220))
        self.output_signal_graph.setLabel("bottom", text="Time(sec)")
        self.output_signal_graph.setLabel("left", text="Amplitude")
        self.output_signal_graph.setObjectName("output_signal_graph")
        self.outputHLayout.addWidget(self.output_signal_graph)
        self.output_spectro = QtWidgets.QFrame(self.tab)
        self.output_spectro.setMinimumSize(QtCore.QSize(660, 220))
        self.output_spectro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output_spectro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_spectro.setObjectName("output_spectro")

        # create a horizontal layout
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout(self.output_spectro)
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        ##Canvas Here
        self.figure_1 = plt.figure()
        self.canvas_1 = FigureCanvas(self.figure_1)
        ##End Of Canvas
        ##Add Canvas
        self.horizontalLayout_59.addWidget(self.canvas_1)
        # end of horizontal layout

        self.outputHLayout.addWidget(self.output_spectro)
        self.SignalsVLayout.addLayout(self.outputHLayout)
        self.hide_output_spectro_checkbox = QtWidgets.QCheckBox(self.tab)
        self.hide_output_spectro_checkbox.setObjectName("hide_output_spectro_checkbox")
        self.SignalsVLayout.addWidget(self.hide_output_spectro_checkbox)
        self.verticalLayout_7.addLayout(self.SignalsVLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.signal_control_groupbox = QtWidgets.QGroupBox(self.tab)
        self.signal_control_groupbox.setObjectName("signal_control_groupbox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.signal_control_groupbox)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.play_pause_btn = QtWidgets.QPushButton(self.signal_control_groupbox)
        self.play_pause_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/newPrefix/Images/play_button.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.play_pause_btn.setIcon(icon)
        self.play_pause_btn.setObjectName("play_pause_btn")
        self.horizontalLayout_7.addWidget(self.play_pause_btn)
        self.reset_btn = QtWidgets.QPushButton(self.signal_control_groupbox)
        self.reset_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/newPrefix/Images/reset_button.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.reset_btn.setIcon(icon1)
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout_7.addWidget(self.reset_btn)
        self.zoomin_btn = QtWidgets.QPushButton(self.signal_control_groupbox)
        self.zoomin_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/newPrefix/Images/zoom_in.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.zoomin_btn.setIcon(icon2)
        self.zoomin_btn.setObjectName("zoomin_btn")
        self.horizontalLayout_7.addWidget(self.zoomin_btn)
        self.zoomout_btn = QtWidgets.QPushButton(self.signal_control_groupbox)
        self.zoomout_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(":/newPrefix/Images/zoom_out.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.zoomout_btn.setIcon(icon3)
        self.zoomout_btn.setObjectName("zoomout_btn")
        self.horizontalLayout_7.addWidget(self.zoomout_btn)
        self.speed_label = QtWidgets.QLabel(self.signal_control_groupbox)
        self.speed_label.setObjectName("speed_label")
        self.horizontalLayout_7.addWidget(self.speed_label)
        self.signal_speed_slider = QtWidgets.QSlider(self.signal_control_groupbox)
        self.signal_speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.signal_speed_slider.setObjectName("signal_speed_slider")
        self.horizontalLayout_7.addWidget(self.signal_speed_slider)
        self.horizontalLayout_8.addWidget(self.signal_control_groupbox)
        self.audio_control_groupbox = QtWidgets.QGroupBox(self.tab)
        self.audio_control_groupbox.setObjectName("audio_control_groupbox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.audio_control_groupbox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.audio_mute_btn = QtWidgets.QPushButton(self.audio_control_groupbox)
        self.audio_mute_btn.setText("")
        self.audio_mute_btn.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(":/newPrefix/Images/unmute.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.audio_mute_btn.setIcon(icon4)
        self.audio_mute_btn.setObjectName("audio_mute_btn")
        self.horizontalLayout_6.addWidget(self.audio_mute_btn)
        self.audio_volume_slider = QtWidgets.QSlider(self.audio_control_groupbox)
        self.audio_volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.audio_volume_slider.setObjectName("audio_volume_slider")
        self.horizontalLayout_6.addWidget(self.audio_volume_slider)
        self.audio_select_radiobtn = QtWidgets.QRadioButton(self.audio_control_groupbox)
        self.audio_select_radiobtn.setObjectName("audio_select_radiobtn")
        self.horizontalLayout_6.addWidget(self.audio_select_radiobtn)
        self.horizontalLayout_8.addWidget(self.audio_control_groupbox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.fft_graph = PlotWidget(self.frame)
        self.fft_graph.setMinimumSize(QtCore.QSize(660, 180))
        self.fft_graph.setObjectName("fft_graph")
        self.fft_graph.setLabel("bottom", text="Frequency(Hz)")
        self.fft_graph.setLabel("left", text="Magnitude")
        self.verticalLayout.addWidget(self.fft_graph)
        self.horizontalLayout_5.addWidget(self.frame)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.window_label = QtWidgets.QLabel(self.groupBox)
        self.window_label.setObjectName("window_label")
        self.horizontalLayout_2.addWidget(self.window_label)
        self.window_combobox = QtWidgets.QComboBox(self.groupBox)
        self.window_combobox.setMinimumSize(QtCore.QSize(200, 0))
        self.window_combobox.setObjectName("window_combobox")
        self.horizontalLayout_2.addWidget(self.window_combobox)
        self.std_label = QtWidgets.QLabel(self.groupBox)
        self.std_label.setObjectName("std_label")
        self.horizontalLayout_2.addWidget(self.std_label)
        self.std_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.std_doubleSpinBox.setObjectName("std_doubleSpinBox")
        self.horizontalLayout_2.addWidget(self.std_doubleSpinBox)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_74 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_74.setObjectName("horizontalLayout_74")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem1)
        self.drum_slider = QtWidgets.QSlider(self.groupBox)
        self.drum_slider.setOrientation(QtCore.Qt.Vertical)
        self.drum_slider.setObjectName("drum_slider")
        self.horizontalLayout.addWidget(self.drum_slider)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem3)
        self.drum_image = QtWidgets.QLabel(self.groupBox)
        self.drum_image.setMinimumSize(QtCore.QSize(50, 40))
        self.drum_image.setMaximumSize(QtCore.QSize(50, 40))
        self.drum_image.setStyleSheet(
            "background-image: url(:/newPrefix/Images/Drums.png)"
        )
        self.drum_image.setText("")
        self.drum_image.setPixmap(QtGui.QPixmap(":/newPrefix/Images/Drums.png"))
        self.drum_image.setScaledContents(True)
        self.drum_image.setObjectName("drum_image")
        self.horizontalLayout_4.addWidget(self.drum_image)
        spacerItem4 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_74.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        spacerItem5 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_69.addItem(spacerItem5)
        self.violin_slider = QtWidgets.QSlider(self.groupBox)
        self.violin_slider.setOrientation(QtCore.Qt.Vertical)
        self.violin_slider.setObjectName("violin_slider")
        self.horizontalLayout_69.addWidget(self.violin_slider)
        spacerItem6 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_69.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_69)
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        spacerItem7 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_68.addItem(spacerItem7)
        self.violin_image = QtWidgets.QLabel(self.groupBox)
        self.violin_image.setMinimumSize(QtCore.QSize(50, 40))
        self.violin_image.setMaximumSize(QtCore.QSize(50, 40))
        self.violin_image.setText("")
        self.violin_image.setPixmap(QtGui.QPixmap(":/newPrefix/Images/violin.png"))
        self.violin_image.setScaledContents(True)
        self.violin_image.setObjectName("violin_image")
        self.horizontalLayout_68.addWidget(self.violin_image)
        spacerItem8 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_68.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_68)
        self.horizontalLayout_74.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_70 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_70.setObjectName("horizontalLayout_70")
        spacerItem9 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_70.addItem(spacerItem9)
        self.piano_slider = QtWidgets.QSlider(self.groupBox)
        self.piano_slider.setOrientation(QtCore.Qt.Vertical)
        self.piano_slider.setObjectName("piano_slider")
        self.horizontalLayout_70.addWidget(self.piano_slider)
        spacerItem10 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_70.addItem(spacerItem10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_70)
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        spacerItem11 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_71.addItem(spacerItem11)
        self.piano_image = QtWidgets.QLabel(self.groupBox)
        self.piano_image.setMinimumSize(QtCore.QSize(50, 40))
        self.piano_image.setMaximumSize(QtCore.QSize(50, 40))
        self.piano_image.setText("")
        self.piano_image.setPixmap(QtGui.QPixmap(":/newPrefix/Images/piano.png"))
        self.piano_image.setScaledContents(True)
        self.piano_image.setObjectName("piano_image")
        self.horizontalLayout_71.addWidget(self.piano_image)
        spacerItem12 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_71.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_71)
        self.horizontalLayout_74.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_73 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_73.setObjectName("horizontalLayout_73")
        spacerItem13 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_73.addItem(spacerItem13)
        self.trumpet_slider = QtWidgets.QSlider(self.groupBox)
        self.trumpet_slider.setOrientation(QtCore.Qt.Vertical)
        self.trumpet_slider.setObjectName("trumpet_slider")
        self.horizontalLayout_73.addWidget(self.trumpet_slider)
        spacerItem14 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_73.addItem(spacerItem14)
        self.verticalLayout_5.addLayout(self.horizontalLayout_73)
        self.horizontalLayout_72 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_72.setObjectName("horizontalLayout_72")
        spacerItem15 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_72.addItem(spacerItem15)
        self.trumpet_image = QtWidgets.QLabel(self.groupBox)
        self.trumpet_image.setMinimumSize(QtCore.QSize(50, 40))
        self.trumpet_image.setMaximumSize(QtCore.QSize(50, 40))
        self.trumpet_image.setText("")
        self.trumpet_image.setPixmap(QtGui.QPixmap(":/newPrefix/Images/Trumpet.png"))
        self.trumpet_image.setScaledContents(True)
        self.trumpet_image.setObjectName("trumpet_image")
        self.horizontalLayout_72.addWidget(self.trumpet_image)
        spacerItem16 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_72.addItem(spacerItem16)
        self.verticalLayout_5.addLayout(self.horizontalLayout_72)
        self.horizontalLayout_74.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_74)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.input_signal_graph_2 = PlotWidget(self.tab_2)
        self.input_signal_graph_2.setMinimumSize(QtCore.QSize(660, 200))
        self.input_signal_graph_2.setMaximumSize(QtCore.QSize(5000, 220))
        self.input_signal_graph_2.setLabel("bottom", text="Time(sec)")
        self.input_signal_graph_2.setLabel("left", text="Amplitude")
        self.input_signal_graph_2.setObjectName("input_signal_graph_2")
        self.horizontalLayout_10.addWidget(self.input_signal_graph_2)
        self.input_spectro_2 = QtWidgets.QFrame(self.tab_2)
        self.input_spectro_2.setMinimumSize(QtCore.QSize(660, 220))
        self.input_spectro_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_spectro_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_spectro_2.setObjectName("input_spectro_2")

        # create a horizontal layout
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout(self.input_spectro_2)
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        ##Canvas Here
        self.figure_2 = plt.figure()
        self.canvas_2 = FigureCanvas(self.figure_2)
        ##End Of Canvas
        ##Add Canvas
        self.horizontalLayout_60.addWidget(self.canvas_2)
        # end of horizontal layout

        self.horizontalLayout_10.addWidget(self.input_spectro_2)
        self.verticalLayout_41.addLayout(self.horizontalLayout_10)
        self.hide_input_spectro_checkbox_2 = QtWidgets.QCheckBox(self.tab_2)
        self.hide_input_spectro_checkbox_2.setObjectName(
            "hide_input_spectro_checkbox_2"
        )
        self.verticalLayout_41.addWidget(self.hide_input_spectro_checkbox_2)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.output_signal_graph_2 = PlotWidget(self.tab_2)
        self.output_signal_graph_2.setMinimumSize(QtCore.QSize(660, 200))
        self.output_signal_graph_2.setMaximumSize(QtCore.QSize(5000, 220))
        self.output_signal_graph_2.setLabel("bottom", text="Time(sec)")
        self.output_signal_graph_2.setLabel("left", text="Amplitude")
        self.output_signal_graph_2.setObjectName("output_signal_graph_2")
        self.horizontalLayout_9.addWidget(self.output_signal_graph_2)
        self.output_spectro_2 = QtWidgets.QFrame(self.tab_2)
        self.output_spectro_2.setMinimumSize(QtCore.QSize(660, 220))
        self.output_spectro_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output_spectro_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_spectro_2.setObjectName("output_spectro_2")

        # create a horizontal layout
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout(self.output_spectro_2)
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        ##Canvas Here
        self.figure_3 = plt.figure()
        self.canvas_3 = FigureCanvas(self.figure_3)
        ##End Of Canvas
        ##Add Canvas
        self.horizontalLayout_61.addWidget(self.canvas_3)
        # end of horizontal layout

        self.horizontalLayout_9.addWidget(self.output_spectro_2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        self.hide_output_spectro_checkbox_2 = QtWidgets.QCheckBox(self.tab_2)
        self.hide_output_spectro_checkbox_2.setObjectName(
            "hide_output_spectro_checkbox_2"
        )
        self.verticalLayout_13.addWidget(self.hide_output_spectro_checkbox_2)
        self.verticalLayout_41.addLayout(self.verticalLayout_13)
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.signal_control_groupbox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.signal_control_groupbox_2.setObjectName("signal_control_groupbox_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.signal_control_groupbox_2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.play_pause_btn_2 = QtWidgets.QPushButton(self.signal_control_groupbox_2)
        self.play_pause_btn_2.setText("")
        self.play_pause_btn_2.setIcon(icon)
        self.play_pause_btn_2.setObjectName("play_pause_btn_2")
        self.horizontalLayout_12.addWidget(self.play_pause_btn_2)
        self.reset_btn_2 = QtWidgets.QPushButton(self.signal_control_groupbox_2)
        self.reset_btn_2.setText("")
        self.reset_btn_2.setIcon(icon1)
        self.reset_btn_2.setObjectName("reset_btn_2")
        self.horizontalLayout_12.addWidget(self.reset_btn_2)
        self.zoomin_btn_2 = QtWidgets.QPushButton(self.signal_control_groupbox_2)
        self.zoomin_btn_2.setText("")
        self.zoomin_btn_2.setIcon(icon2)
        self.zoomin_btn_2.setObjectName("zoomin_btn_2")
        self.horizontalLayout_12.addWidget(self.zoomin_btn_2)
        self.zoomout_btn_2 = QtWidgets.QPushButton(self.signal_control_groupbox_2)
        self.zoomout_btn_2.setText("")
        self.zoomout_btn_2.setIcon(icon3)
        self.zoomout_btn_2.setObjectName("zoomout_btn_2")
        self.horizontalLayout_12.addWidget(self.zoomout_btn_2)
        self.speed_label_2 = QtWidgets.QLabel(self.signal_control_groupbox_2)
        self.speed_label_2.setObjectName("speed_label_2")
        self.horizontalLayout_12.addWidget(self.speed_label_2)
        self.signal_speed_slider_2 = QtWidgets.QSlider(self.signal_control_groupbox_2)
        self.signal_speed_slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.signal_speed_slider_2.setObjectName("signal_speed_slider_2")
        self.horizontalLayout_12.addWidget(self.signal_speed_slider_2)
        self.horizontalLayout_13.addWidget(self.signal_control_groupbox_2)
        self.audio_control_groupbox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.audio_control_groupbox_2.setObjectName("audio_control_groupbox_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.audio_control_groupbox_2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.audio_mute_btn_2 = QtWidgets.QPushButton(self.audio_control_groupbox_2)
        self.audio_mute_btn_2.setText("")
        self.audio_mute_btn_2.setIcon(icon4)
        self.audio_mute_btn_2.setObjectName("audio_mute_btn_2")
        self.horizontalLayout_11.addWidget(self.audio_mute_btn_2)
        self.audio_volume_slider_2 = QtWidgets.QSlider(self.audio_control_groupbox_2)
        self.audio_volume_slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.audio_volume_slider_2.setObjectName("audio_volume_slider_2")
        self.horizontalLayout_11.addWidget(self.audio_volume_slider_2)
        self.audio_select_radiobtn_2 = QtWidgets.QRadioButton(
            self.audio_control_groupbox_2
        )
        self.audio_select_radiobtn_2.setObjectName("audio_select_radiobtn_2")
        self.horizontalLayout_11.addWidget(self.audio_select_radiobtn_2)
        self.horizontalLayout_13.addWidget(self.audio_control_groupbox_2)
        self.verticalLayout_40.addLayout(self.horizontalLayout_13)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.frame_2 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_14.addWidget(self.label_2)
        self.fft_graph_2 = PlotWidget(self.frame_2)
        self.fft_graph_2.setMinimumSize(QtCore.QSize(660, 180))
        self.fft_graph_2.setObjectName("fft_graph_2")
        self.fft_graph_2.setLabel("bottom", text="Frequency(Hz)")
        self.fft_graph_2.setLabel("left", text="Magnitude")
        self.verticalLayout_14.addWidget(self.fft_graph_2)
        self.horizontalLayout_24.addWidget(self.frame_2)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.window_label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.window_label_2.setObjectName("window_label_2")
        self.horizontalLayout_23.addWidget(self.window_label_2)
        self.window_combobox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.window_combobox_2.setMinimumSize(QtCore.QSize(200, 0))
        self.window_combobox_2.setObjectName("window_combobox_2")
        self.horizontalLayout_23.addWidget(self.window_combobox_2)
        self.std_label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.std_label_2.setObjectName("std_label_2")
        self.horizontalLayout_23.addWidget(self.std_label_2)
        self.std_doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.std_doubleSpinBox_2.setObjectName("std_doubleSpinBox_2")
        self.horizontalLayout_23.addWidget(self.std_doubleSpinBox_2)
        spacerItem17 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_23.addItem(spacerItem17)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem18 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_14.addItem(spacerItem18)
        self.cat_slider = QtWidgets.QSlider(self.groupBox_2)
        self.cat_slider.setOrientation(QtCore.Qt.Vertical)
        self.cat_slider.setObjectName("cat_slider")
        self.horizontalLayout_14.addWidget(self.cat_slider)
        spacerItem19 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_14.addItem(spacerItem19)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem20 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_15.addItem(spacerItem20)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setMinimumSize(QtCore.QSize(50, 40))
        self.label_7.setMaximumSize(QtCore.QSize(50, 40))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/newPrefix/Images/dolphin.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_15.addWidget(self.label_7)
        spacerItem21 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_15.addItem(spacerItem21)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_22.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem22 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_16.addItem(spacerItem22)
        self.dog_slider = QtWidgets.QSlider(self.groupBox_2)
        self.dog_slider.setOrientation(QtCore.Qt.Vertical)
        self.dog_slider.setObjectName("dog_slider")
        self.horizontalLayout_16.addWidget(self.dog_slider)
        spacerItem23 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_16.addItem(spacerItem23)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem24 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_17.addItem(spacerItem24)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setMinimumSize(QtCore.QSize(50, 40))
        self.label_8.setMaximumSize(QtCore.QSize(50, 40))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/newPrefix/Images/wolf.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_17.addWidget(self.label_8)
        spacerItem25 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_17.addItem(spacerItem25)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_22.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem26 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_18.addItem(spacerItem26)
        self.elephant_slider = QtWidgets.QSlider(self.groupBox_2)
        self.elephant_slider.setOrientation(QtCore.Qt.Vertical)
        self.elephant_slider.setObjectName("elephant_slider")
        self.horizontalLayout_18.addWidget(self.elephant_slider)
        spacerItem27 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_18.addItem(spacerItem27)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem28 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_19.addItem(spacerItem28)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setMinimumSize(QtCore.QSize(50, 40))
        self.label_9.setMaximumSize(QtCore.QSize(50, 40))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/newPrefix/Images/bird.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_19.addWidget(self.label_9)
        spacerItem29 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_19.addItem(spacerItem29)
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_22.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem30 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_20.addItem(spacerItem30)
        self.whale_slider = QtWidgets.QSlider(self.groupBox_2)
        self.whale_slider.setOrientation(QtCore.Qt.Vertical)
        self.whale_slider.setObjectName("whale_slider")
        self.horizontalLayout_20.addWidget(self.whale_slider)
        spacerItem31 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_20.addItem(spacerItem31)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem32 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_21.addItem(spacerItem32)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setMinimumSize(QtCore.QSize(50, 40))
        self.label_10.setMaximumSize(QtCore.QSize(50, 40))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/newPrefix/Images/cat.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_21.addWidget(self.label_10)
        spacerItem33 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_21.addItem(spacerItem33)
        self.verticalLayout_11.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_24.addLayout(self.verticalLayout_12)
        self.verticalLayout_40.addWidget(self.groupBox_2)
        self.verticalLayout_41.addLayout(self.verticalLayout_40)
        self.verticalLayout_42.addLayout(self.verticalLayout_41)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.input_signal_graph_3 = PlotWidget(self.tab_3)
        self.input_signal_graph_3.setMinimumSize(QtCore.QSize(660, 200))
        self.input_signal_graph_3.setMaximumSize(QtCore.QSize(5000, 220))
        self.input_signal_graph_3.setLabel("bottom", text="Time(sec)")
        self.input_signal_graph_3.setLabel("left", text="Amplitude")
        self.input_signal_graph_3.setObjectName("input_signal_graph_3")
        self.horizontalLayout_58.addWidget(self.input_signal_graph_3)
        self.input_spectro_3 = QtWidgets.QFrame(self.tab_3)
        self.input_spectro_3.setMinimumSize(QtCore.QSize(660, 220))
        self.input_spectro_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_spectro_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_spectro_3.setObjectName("input_spectro_3")

        # create a horizontal layout
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout(self.input_spectro_3)
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        ##Canvas Here
        self.figure_4 = plt.figure()
        self.canvas_4 = FigureCanvas(self.figure_4)
        ##End Of Canvas
        ##Add Canvas
        self.horizontalLayout_62.addWidget(self.canvas_4)
        # end of horizontal layout

        self.horizontalLayout_58.addWidget(self.input_spectro_3)
        self.verticalLayout_28.addLayout(self.horizontalLayout_58)
        self.hide_input_spectro_checkbox_3 = QtWidgets.QCheckBox(self.tab_3)
        self.hide_input_spectro_checkbox_3.setObjectName(
            "hide_input_spectro_checkbox_3"
        )
        self.verticalLayout_28.addWidget(self.hide_input_spectro_checkbox_3)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.output_signal_graph_3 = PlotWidget(self.tab_3)
        self.output_signal_graph_3.setMinimumSize(QtCore.QSize(660, 200))
        self.output_signal_graph_3.setMaximumSize(QtCore.QSize(5000, 220))
        self.output_signal_graph_3.setLabel("bottom", text="Time(sec)")
        self.output_signal_graph_3.setLabel("left", text="Amplitude")
        self.output_signal_graph_3.setObjectName("output_signal_graph_3")
        self.horizontalLayout_25.addWidget(self.output_signal_graph_3)
        self.output_spectro_3 = QtWidgets.QFrame(self.tab_3)
        self.output_spectro_3.setMinimumSize(QtCore.QSize(660, 220))
        self.output_spectro_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output_spectro_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_spectro_3.setObjectName("output_spectro_3")

        # create a horizontal layout
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout(self.output_spectro_3)
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        ##Canvas Here
        self.figure_5 = plt.figure()
        self.canvas_5 = FigureCanvas(self.figure_5)
        ##End Of Canvas
        ##Add Canvas
        self.horizontalLayout_63.addWidget(self.canvas_5)
        # end of horizontal layout

        self.horizontalLayout_25.addWidget(self.output_spectro_3)
        self.verticalLayout_28.addLayout(self.horizontalLayout_25)
        self.hide_output_spectro_checkbox_3 = QtWidgets.QCheckBox(self.tab_3)
        self.hide_output_spectro_checkbox_3.setObjectName(
            "hide_output_spectro_checkbox_3"
        )
        self.verticalLayout_28.addWidget(self.hide_output_spectro_checkbox_3)
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.signal_control_groupbox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.signal_control_groupbox_3.setObjectName("signal_control_groupbox_3")
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout(self.signal_control_groupbox_3)
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.play_pause_btn_3 = QtWidgets.QPushButton(self.signal_control_groupbox_3)
        self.play_pause_btn_3.setText("")
        self.play_pause_btn_3.setIcon(icon)
        self.play_pause_btn_3.setObjectName("play_pause_btn_3")
        self.horizontalLayout_60.addWidget(self.play_pause_btn_3)
        self.reset_btn_3 = QtWidgets.QPushButton(self.signal_control_groupbox_3)
        self.reset_btn_3.setText("")
        self.reset_btn_3.setIcon(icon1)
        self.reset_btn_3.setObjectName("reset_btn_3")
        self.horizontalLayout_60.addWidget(self.reset_btn_3)
        self.zoomin_btn_3 = QtWidgets.QPushButton(self.signal_control_groupbox_3)
        self.zoomin_btn_3.setText("")
        self.zoomin_btn_3.setIcon(icon2)
        self.zoomin_btn_3.setObjectName("zoomin_btn_3")
        self.horizontalLayout_60.addWidget(self.zoomin_btn_3)
        self.zoomout_btn_3 = QtWidgets.QPushButton(self.signal_control_groupbox_3)
        self.zoomout_btn_3.setText("")
        self.zoomout_btn_3.setIcon(icon3)
        self.zoomout_btn_3.setObjectName("zoomout_btn_3")
        self.horizontalLayout_60.addWidget(self.zoomout_btn_3)
        self.speed_label_3 = QtWidgets.QLabel(self.signal_control_groupbox_3)
        self.speed_label_3.setObjectName("speed_label_3")
        self.horizontalLayout_60.addWidget(self.speed_label_3)
        self.signal_speed_slider_3 = QtWidgets.QSlider(self.signal_control_groupbox_3)
        self.signal_speed_slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.signal_speed_slider_3.setObjectName("signal_speed_slider_3")
        self.horizontalLayout_60.addWidget(self.signal_speed_slider_3)
        self.horizontalLayout_61.addWidget(self.signal_control_groupbox_3)
        self.audio_control_groupbox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.audio_control_groupbox_3.setObjectName("audio_control_groupbox_3")
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout(self.audio_control_groupbox_3)
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.audio_mute_btn_3 = QtWidgets.QPushButton(self.audio_control_groupbox_3)
        self.audio_mute_btn_3.setText("")
        self.audio_mute_btn_3.setIcon(icon4)
        self.audio_mute_btn_3.setObjectName("audio_mute_btn_3")
        self.horizontalLayout_59.addWidget(self.audio_mute_btn_3)
        self.audio_volume_slider_3 = QtWidgets.QSlider(self.audio_control_groupbox_3)
        self.audio_volume_slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.audio_volume_slider_3.setObjectName("audio_volume_slider_3")
        self.horizontalLayout_59.addWidget(self.audio_volume_slider_3)
        self.audio_select_radiobtn_3 = QtWidgets.QRadioButton(
            self.audio_control_groupbox_3
        )
        self.audio_select_radiobtn_3.setObjectName("audio_select_radiobtn_3")
        self.horizontalLayout_59.addWidget(self.audio_select_radiobtn_3)
        self.horizontalLayout_61.addWidget(self.audio_control_groupbox_3)
        self.verticalLayout_28.addLayout(self.horizontalLayout_61)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_15.addWidget(self.label_3)
        self.fft_graph_3 = PlotWidget(self.frame_4)
        self.fft_graph_3.setMinimumSize(QtCore.QSize(660, 180))
        self.fft_graph_3.setObjectName("fft_graph_3")
        self.fft_graph_3.setLabel("bottom", text="Frequency(Hz)")
        self.fft_graph_3.setLabel("left", text="Magnitude")
        self.verticalLayout_15.addWidget(self.fft_graph_3)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.window_label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.window_label_3.setObjectName("window_label_3")
        self.horizontalLayout_26.addWidget(self.window_label_3)
        self.window_combobox_3 = QtWidgets.QComboBox(self.groupBox_3)
        self.window_combobox_3.setMinimumSize(QtCore.QSize(200, 0))
        self.window_combobox_3.setObjectName("window_combobox_3")
        self.horizontalLayout_26.addWidget(self.window_combobox_3)
        self.std_label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.std_label_3.setObjectName("std_label_3")
        self.horizontalLayout_26.addWidget(self.std_label_3)
        self.std_doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.std_doubleSpinBox_3.setObjectName("std_doubleSpinBox_3")
        self.horizontalLayout_26.addWidget(self.std_doubleSpinBox_3)
        spacerItem34 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_26.addItem(spacerItem34)
        self.verticalLayout_27.addLayout(self.horizontalLayout_26)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem35 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_27.addItem(spacerItem35)
        self.slider_one = QtWidgets.QSlider(self.groupBox_3)
        self.slider_one.setOrientation(QtCore.Qt.Vertical)
        self.slider_one.setObjectName("slider_one")
        self.horizontalLayout_27.addWidget(self.slider_one)
        spacerItem36 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_27.addItem(spacerItem36)
        self.verticalLayout_16.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem37 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_28.addItem(spacerItem37)
        self.label_one = QtWidgets.QLabel(self.groupBox_3)
        self.label_one.setObjectName("label_one")
        self.horizontalLayout_28.addWidget(self.label_one)
        spacerItem38 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_28.addItem(spacerItem38)
        self.verticalLayout_16.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_47.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        spacerItem39 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_29.addItem(spacerItem39)
        self.slider_two = QtWidgets.QSlider(self.groupBox_3)
        self.slider_two.setOrientation(QtCore.Qt.Vertical)
        self.slider_two.setObjectName("slider_two")
        self.horizontalLayout_29.addWidget(self.slider_two)
        spacerItem40 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_29.addItem(spacerItem40)
        self.verticalLayout_17.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        spacerItem41 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_30.addItem(spacerItem41)
        self.label_two = QtWidgets.QLabel(self.groupBox_3)
        self.label_two.setObjectName("label_two")
        self.horizontalLayout_30.addWidget(self.label_two)
        spacerItem42 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_30.addItem(spacerItem42)
        self.verticalLayout_17.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_47.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        spacerItem43 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_31.addItem(spacerItem43)
        self.slider_three = QtWidgets.QSlider(self.groupBox_3)
        self.slider_three.setOrientation(QtCore.Qt.Vertical)
        self.slider_three.setObjectName("slider_three")
        self.horizontalLayout_31.addWidget(self.slider_three)
        spacerItem44 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_31.addItem(spacerItem44)
        self.verticalLayout_18.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        spacerItem45 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_32.addItem(spacerItem45)
        self.label_three = QtWidgets.QLabel(self.groupBox_3)
        self.label_three.setObjectName("label_three")
        self.horizontalLayout_32.addWidget(self.label_three)
        spacerItem46 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_32.addItem(spacerItem46)
        self.verticalLayout_18.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_47.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        spacerItem47 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_33.addItem(spacerItem47)
        self.slider_four = QtWidgets.QSlider(self.groupBox_3)
        self.slider_four.setOrientation(QtCore.Qt.Vertical)
        self.slider_four.setObjectName("slider_four")
        self.horizontalLayout_33.addWidget(self.slider_four)
        spacerItem48 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_33.addItem(spacerItem48)
        self.verticalLayout_19.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        spacerItem49 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_34.addItem(spacerItem49)
        self.label_four = QtWidgets.QLabel(self.groupBox_3)
        self.label_four.setObjectName("label_four")
        self.horizontalLayout_34.addWidget(self.label_four)
        spacerItem50 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_34.addItem(spacerItem50)
        self.verticalLayout_19.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_47.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        spacerItem51 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_35.addItem(spacerItem51)
        self.slider_five = QtWidgets.QSlider(self.groupBox_3)
        self.slider_five.setOrientation(QtCore.Qt.Vertical)
        self.slider_five.setObjectName("slider_five")
        self.horizontalLayout_35.addWidget(self.slider_five)
        spacerItem52 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_35.addItem(spacerItem52)
        self.verticalLayout_20.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        spacerItem53 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_36.addItem(spacerItem53)
        self.label_five = QtWidgets.QLabel(self.groupBox_3)
        self.label_five.setObjectName("label_five")
        self.horizontalLayout_36.addWidget(self.label_five)
        spacerItem54 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_36.addItem(spacerItem54)
        self.verticalLayout_20.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_47.addLayout(self.verticalLayout_20)
        self.verticalLayout_26.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        spacerItem55 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_37.addItem(spacerItem55)
        self.slider_six = QtWidgets.QSlider(self.groupBox_3)
        self.slider_six.setOrientation(QtCore.Qt.Vertical)
        self.slider_six.setObjectName("slider_six")
        self.horizontalLayout_37.addWidget(self.slider_six)
        spacerItem56 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_37.addItem(spacerItem56)
        self.verticalLayout_21.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        spacerItem57 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_38.addItem(spacerItem57)
        self.label_six = QtWidgets.QLabel(self.groupBox_3)
        self.label_six.setObjectName("label_six")
        self.horizontalLayout_38.addWidget(self.label_six)
        spacerItem58 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_38.addItem(spacerItem58)
        self.verticalLayout_21.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_48.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        spacerItem59 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_39.addItem(spacerItem59)
        self.slider_seven = QtWidgets.QSlider(self.groupBox_3)
        self.slider_seven.setOrientation(QtCore.Qt.Vertical)
        self.slider_seven.setObjectName("slider_seven")
        self.horizontalLayout_39.addWidget(self.slider_seven)
        spacerItem60 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_39.addItem(spacerItem60)
        self.verticalLayout_22.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        spacerItem61 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_40.addItem(spacerItem61)
        self.label_seven = QtWidgets.QLabel(self.groupBox_3)
        self.label_seven.setObjectName("label_seven")
        self.horizontalLayout_40.addWidget(self.label_seven)
        spacerItem62 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_40.addItem(spacerItem62)
        self.verticalLayout_22.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_48.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        spacerItem63 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_41.addItem(spacerItem63)
        self.slider_eight = QtWidgets.QSlider(self.groupBox_3)
        self.slider_eight.setOrientation(QtCore.Qt.Vertical)
        self.slider_eight.setObjectName("slider_eight")
        self.horizontalLayout_41.addWidget(self.slider_eight)
        spacerItem64 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_41.addItem(spacerItem64)
        self.verticalLayout_23.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        spacerItem65 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_42.addItem(spacerItem65)
        self.label_eight = QtWidgets.QLabel(self.groupBox_3)
        self.label_eight.setObjectName("label_eight")
        self.horizontalLayout_42.addWidget(self.label_eight)
        spacerItem66 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_42.addItem(spacerItem66)
        self.verticalLayout_23.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_48.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        spacerItem67 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_43.addItem(spacerItem67)
        self.slider_nine = QtWidgets.QSlider(self.groupBox_3)
        self.slider_nine.setOrientation(QtCore.Qt.Vertical)
        self.slider_nine.setObjectName("slider_nine")
        self.horizontalLayout_43.addWidget(self.slider_nine)
        spacerItem68 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_43.addItem(spacerItem68)
        self.verticalLayout_24.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        spacerItem69 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_44.addItem(spacerItem69)
        self.label_nine = QtWidgets.QLabel(self.groupBox_3)
        self.label_nine.setObjectName("label_nine")
        self.horizontalLayout_44.addWidget(self.label_nine)
        spacerItem70 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_44.addItem(spacerItem70)
        self.verticalLayout_24.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_48.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        spacerItem71 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_45.addItem(spacerItem71)
        self.slider_ten = QtWidgets.QSlider(self.groupBox_3)
        self.slider_ten.setOrientation(QtCore.Qt.Vertical)
        self.slider_ten.setObjectName("slider_ten")
        self.horizontalLayout_45.addWidget(self.slider_ten)
        spacerItem72 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_45.addItem(spacerItem72)
        self.verticalLayout_25.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        spacerItem73 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_46.addItem(spacerItem73)
        self.label_ten = QtWidgets.QLabel(self.groupBox_3)
        self.label_ten.setObjectName("label_ten")
        self.horizontalLayout_46.addWidget(self.label_ten)
        spacerItem74 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_46.addItem(spacerItem74)
        self.verticalLayout_25.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_48.addLayout(self.verticalLayout_25)
        self.verticalLayout_26.addLayout(self.horizontalLayout_48)
        self.verticalLayout_27.addLayout(self.verticalLayout_26)
        self.horizontalLayout_3.addLayout(self.verticalLayout_27)
        self.verticalLayout_28.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.input_signal_graph_4 = PlotWidget(self.tab_4)
        self.input_signal_graph_4.setMinimumSize(QtCore.QSize(660, 200))
        self.input_signal_graph_4.setMaximumSize(QtCore.QSize(16777215, 220))
        self.input_signal_graph_4.setLabel("bottom", text="Time(sec)")
        self.input_signal_graph_4.setLabel("left", text="Amplitude")
        self.input_signal_graph_4.setObjectName("input_signal_graph_4")
        self.horizontalLayout_63.addWidget(self.input_signal_graph_4)
        self.input_spectro_4 = QtWidgets.QFrame(self.tab_4)
        self.input_spectro_4.setMinimumSize(QtCore.QSize(660, 220))
        self.input_spectro_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_spectro_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_spectro_4.setObjectName("input_spectro_4")

        # create a horizontal layout
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout(self.input_spectro_4)
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        ##Canvas Here
        self.figure_6 = plt.figure()
        self.canvas_6 = FigureCanvas(self.figure_6)
        ##End Of Canvas
        ##Add Canvas
        self.horizontalLayout_64.addWidget(self.canvas_6)
        # end of horizontal layout

        self.horizontalLayout_63.addWidget(self.input_spectro_4)
        self.verticalLayout_29.addLayout(self.horizontalLayout_63)
        self.hide_input_spectro_checkbox_4 = QtWidgets.QCheckBox(self.tab_4)
        self.hide_input_spectro_checkbox_4.setObjectName(
            "hide_input_spectro_checkbox_4"
        )
        self.verticalLayout_29.addWidget(self.hide_input_spectro_checkbox_4)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.output_signal_graph_4 = PlotWidget(self.tab_4)
        self.output_signal_graph_4.setMinimumSize(QtCore.QSize(660, 200))
        self.output_signal_graph_4.setMaximumSize(QtCore.QSize(5000, 220))
        self.output_signal_graph_4.setLabel("bottom", text="Time(sec)")
        self.output_signal_graph_4.setLabel("left", text="Amplitude")
        self.output_signal_graph_4.setObjectName("output_signal_graph_4")
        self.horizontalLayout_57.addWidget(self.output_signal_graph_4)
        self.output_spectro_4 = QtWidgets.QFrame(self.tab_4)
        self.output_spectro_4.setMinimumSize(QtCore.QSize(660, 220))
        self.output_spectro_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output_spectro_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_spectro_4.setObjectName("output_spectro_4")

        # create a horizontal layout
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout(self.output_spectro_4)
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        ##Canvas Here
        self.figure_7 = plt.figure()
        self.canvas_7 = FigureCanvas(self.figure_7)
        ##End Of Canvas
        ##Add Canvas
        self.horizontalLayout_65.addWidget(self.canvas_7)
        # end of horizontal layout

        self.horizontalLayout_57.addWidget(self.output_spectro_4)
        self.verticalLayout_29.addLayout(self.horizontalLayout_57)
        self.hide_output_spectro_checkbox_4 = QtWidgets.QCheckBox(self.tab_4)
        self.hide_output_spectro_checkbox_4.setObjectName(
            "hide_output_spectro_checkbox_4"
        )
        self.verticalLayout_29.addWidget(self.hide_output_spectro_checkbox_4)
        self.verticalLayout_31.addLayout(self.verticalLayout_29)
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        self.signal_control_groupbox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.signal_control_groupbox_4.setObjectName("signal_control_groupbox_4")
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout(self.signal_control_groupbox_4)
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.play_pause_btn_4 = QtWidgets.QPushButton(self.signal_control_groupbox_4)
        self.play_pause_btn_4.setText("")
        self.play_pause_btn_4.setIcon(icon)
        self.play_pause_btn_4.setObjectName("play_pause_btn_4")
        self.horizontalLayout_64.addWidget(self.play_pause_btn_4)
        self.reset_btn_4 = QtWidgets.QPushButton(self.signal_control_groupbox_4)
        self.reset_btn_4.setText("")
        self.reset_btn_4.setIcon(icon1)
        self.reset_btn_4.setObjectName("reset_btn_4")
        self.horizontalLayout_64.addWidget(self.reset_btn_4)
        self.zoomin_btn_4 = QtWidgets.QPushButton(self.signal_control_groupbox_4)
        self.zoomin_btn_4.setText("")
        self.zoomin_btn_4.setIcon(icon2)
        self.zoomin_btn_4.setObjectName("zoomin_btn_4")
        self.horizontalLayout_64.addWidget(self.zoomin_btn_4)
        self.zoomout_btn_4 = QtWidgets.QPushButton(self.signal_control_groupbox_4)
        self.zoomout_btn_4.setText("")
        self.zoomout_btn_4.setIcon(icon3)
        self.zoomout_btn_4.setObjectName("zoomout_btn_4")
        self.horizontalLayout_64.addWidget(self.zoomout_btn_4)
        self.speed_label_4 = QtWidgets.QLabel(self.signal_control_groupbox_4)
        self.speed_label_4.setObjectName("speed_label_4")
        self.horizontalLayout_64.addWidget(self.speed_label_4)
        self.signal_speed_slider_4 = QtWidgets.QSlider(self.signal_control_groupbox_4)
        self.signal_speed_slider_4.setOrientation(QtCore.Qt.Horizontal)
        self.signal_speed_slider_4.setObjectName("signal_speed_slider_4")
        self.horizontalLayout_64.addWidget(self.signal_speed_slider_4)
        self.horizontalLayout_66.addWidget(self.signal_control_groupbox_4)
        self.audio_control_groupbox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.audio_control_groupbox_4.setObjectName("audio_control_groupbox_4")
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout(self.audio_control_groupbox_4)
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.audio_mute_btn_4 = QtWidgets.QPushButton(self.audio_control_groupbox_4)
        self.audio_mute_btn_4.setText("")
        self.audio_mute_btn_4.setIcon(icon4)
        self.audio_mute_btn_4.setObjectName("audio_mute_btn_4")
        self.horizontalLayout_65.addWidget(self.audio_mute_btn_4)
        self.audio_volume_slider_4 = QtWidgets.QSlider(self.audio_control_groupbox_4)
        self.audio_volume_slider_4.setOrientation(QtCore.Qt.Horizontal)
        self.audio_volume_slider_4.setObjectName("audio_volume_slider_4")
        self.horizontalLayout_65.addWidget(self.audio_volume_slider_4)
        self.audio_select_radiobtn_4 = QtWidgets.QRadioButton(
            self.audio_control_groupbox_4
        )
        self.audio_select_radiobtn_4.setObjectName("audio_select_radiobtn_4")
        self.horizontalLayout_65.addWidget(self.audio_select_radiobtn_4)
        self.horizontalLayout_66.addWidget(self.audio_control_groupbox_4)
        self.verticalLayout_31.addLayout(self.horizontalLayout_66)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.frame_5 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_30.addWidget(self.label_4)
        self.fft_graph_4 = PlotWidget(self.frame_5)
        self.fft_graph_4.setMinimumSize(QtCore.QSize(660, 180))
        self.fft_graph_4.setObjectName("fft_graph_4")
        self.fft_graph_4.setLabel("bottom", text="Frequency(Hz)")
        self.fft_graph_4.setLabel("left", text="Magnitude")
        self.verticalLayout_30.addWidget(self.fft_graph_4)
        self.horizontalLayout_62.addWidget(self.frame_5)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.window_label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.window_label_4.setObjectName("window_label_4")
        self.horizontalLayout_49.addWidget(self.window_label_4)
        self.window_combobox_4 = QtWidgets.QComboBox(self.groupBox_4)
        self.window_combobox_4.setMinimumSize(QtCore.QSize(200, 0))
        self.window_combobox_4.setObjectName("window_combobox_4")
        self.horizontalLayout_49.addWidget(self.window_combobox_4)
        self.std_label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.std_label_4.setObjectName("std_label_4")
        self.horizontalLayout_49.addWidget(self.std_label_4)
        self.std_doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.std_doubleSpinBox_4.setObjectName("std_doubleSpinBox_4")
        self.horizontalLayout_49.addWidget(self.std_doubleSpinBox_4)
        spacerItem75 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_49.addItem(spacerItem75)
        self.verticalLayout_35.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        spacerItem76 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_50.addItem(spacerItem76)
        self.af_slider = QtWidgets.QSlider(self.groupBox_4)
        self.af_slider.setOrientation(QtCore.Qt.Vertical)
        self.af_slider.setObjectName("af_slider")
        self.horizontalLayout_50.addWidget(self.af_slider)
        self.af_slider.setMinimum(0)
        self.af_slider.setMaximum(150)
        spacerItem77 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_50.addItem(spacerItem77)
        self.verticalLayout_32.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        spacerItem78 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_51.addItem(spacerItem78)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_51.addWidget(self.label_15)
        spacerItem79 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_51.addItem(spacerItem79)
        self.verticalLayout_32.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_56.addLayout(self.verticalLayout_32)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        spacerItem80 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_52.addItem(spacerItem80)
        self.rbb_slider = QtWidgets.QSlider(self.groupBox_4)
        self.rbb_slider.setOrientation(QtCore.Qt.Vertical)
        self.rbb_slider.setObjectName("rbb_slider")
        self.horizontalLayout_52.addWidget(self.rbb_slider)

        spacerItem81 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_52.addItem(spacerItem81)
        self.verticalLayout_33.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        spacerItem82 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_53.addItem(spacerItem82)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_53.addWidget(self.label_16)
        spacerItem83 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_53.addItem(spacerItem83)
        self.verticalLayout_33.addLayout(self.horizontalLayout_53)
        self.horizontalLayout_56.addLayout(self.verticalLayout_33)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        spacerItem84 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_54.addItem(spacerItem84)
        self.syn_slider = QtWidgets.QSlider(self.groupBox_4)
        self.syn_slider.setOrientation(QtCore.Qt.Vertical)
        self.syn_slider.setObjectName("syn_slider")
        self.horizontalLayout_54.addWidget(self.syn_slider)
        spacerItem85 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_54.addItem(spacerItem85)
        self.verticalLayout_34.addLayout(self.horizontalLayout_54)
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        spacerItem86 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_55.addItem(spacerItem86)
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_55.addWidget(self.label_17)
        spacerItem87 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_55.addItem(spacerItem87)
        self.verticalLayout_34.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_56.addLayout(self.verticalLayout_34)
        self.verticalLayout_35.addLayout(self.horizontalLayout_56)
        self.horizontalLayout_62.addLayout(self.verticalLayout_35)
        self.verticalLayout_31.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_38.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1416, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Equalizer"))
        self.hide_input_spectro_checkbox.setText(
            _translate("MainWindow", "Hide Input Spectrogram")
        )
        self.hide_output_spectro_checkbox.setText(
            _translate("MainWindow", "Hide Output Spectrogram")
        )
        self.signal_control_groupbox.setTitle(
            _translate("MainWindow", "Signal Control")
        )
        self.speed_label.setText(_translate("MainWindow", "Speed: x"))
        self.audio_control_groupbox.setTitle(_translate("MainWindow", "Audio Control"))
        self.audio_select_radiobtn.setText(
            _translate("MainWindow", "Hear Output Graph")
        )
        self.groupBox.setTitle(_translate("MainWindow", "Equalizer"))
        self.label.setText(_translate("MainWindow", "Frequency Graph"))
        self.window_label.setText(_translate("MainWindow", "Smoothing Window"))
        self.std_label.setText(_translate("MainWindow", "STD"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab),
            _translate("MainWindow", "Musical Instruments"),
        )
        self.hide_input_spectro_checkbox_2.setText(
            _translate("MainWindow", "Hide Input Spectrogram")
        )
        self.hide_output_spectro_checkbox_2.setText(
            _translate("MainWindow", "Hide Output Spectrogram")
        )
        self.signal_control_groupbox_2.setTitle(
            _translate("MainWindow", "Signal Control")
        )
        self.speed_label_2.setText(_translate("MainWindow", "Speed: x"))
        self.audio_control_groupbox_2.setTitle(
            _translate("MainWindow", "Audio Control")
        )
        self.audio_select_radiobtn_2.setText(
            _translate("MainWindow", "Hear Output Graph")
        )
        self.groupBox_2.setTitle(_translate("MainWindow", "Equalizer"))
        self.label_2.setText(_translate("MainWindow", "Frequency Graph"))
        self.window_label_2.setText(_translate("MainWindow", "Smoothing Window"))
        self.std_label_2.setText(_translate("MainWindow", "STD"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2),
            _translate("MainWindow", "Animal Sounds"),
        )
        self.hide_input_spectro_checkbox_3.setText(
            _translate("MainWindow", "Hide Input Spectrogram")
        )
        self.hide_output_spectro_checkbox_3.setText(
            _translate("MainWindow", "Hide Output Spectrogram")
        )
        self.signal_control_groupbox_3.setTitle(
            _translate("MainWindow", "Signal Control")
        )
        self.speed_label_3.setText(_translate("MainWindow", "Speed: x"))
        self.audio_control_groupbox_3.setTitle(
            _translate("MainWindow", "Audio Control")
        )
        self.audio_select_radiobtn_3.setText(
            _translate("MainWindow", "Hear Output Graph")
        )
        self.groupBox_3.setTitle(_translate("MainWindow", "Equalizer"))
        self.label_3.setText(_translate("MainWindow", "Frequency Graph"))
        self.window_label_3.setText(_translate("MainWindow", "Smoothing Window"))
        self.std_label_3.setText(_translate("MainWindow", "STD"))
        self.label_one.setText(_translate("MainWindow", "0-10 HZ"))
        self.label_two.setText(_translate("MainWindow", "10-20 HZ"))
        self.label_three.setText(_translate("MainWindow", "20-30 HZ"))
        self.label_four.setText(_translate("MainWindow", "30-40 HZ"))
        self.label_five.setText(_translate("MainWindow", "40-50 HZ"))
        self.label_six.setText(_translate("MainWindow", "50-60 HZ"))
        self.label_seven.setText(_translate("MainWindow", "60-70 HZ"))
        self.label_eight.setText(_translate("MainWindow", "70-80 HZ"))
        self.label_nine.setText(_translate("MainWindow", "80-90 HZ"))
        self.label_ten.setText(_translate("MainWindow", "90-100 HZ"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_3),
            _translate("MainWindow", "Uniform Range"),
        )
        self.hide_input_spectro_checkbox_4.setText(
            _translate("MainWindow", "Hide Input Spectrogram")
        )
        self.hide_output_spectro_checkbox_4.setText(
            _translate("MainWindow", "Hide Output Spectrogram")
        )
        self.signal_control_groupbox_4.setTitle(
            _translate("MainWindow", "Signal Control")
        )
        self.speed_label_4.setText(_translate("MainWindow", "Speed: x"))
        self.audio_control_groupbox_4.setTitle(
            _translate("MainWindow", "Audio Control")
        )
        self.audio_select_radiobtn_4.setText(
            _translate("MainWindow", "Hear Output Graph")
        )
        self.groupBox_4.setTitle(_translate("MainWindow", "Equalizer"))
        self.label_4.setText(_translate("MainWindow", "Frequency Graph"))
        self.window_label_4.setText(_translate("MainWindow", "Smoothing Window"))
        self.std_label_4.setText(_translate("MainWindow", "STD"))
        self.label_15.setText(_translate("MainWindow", "AF"))
        self.label_16.setText(_translate("MainWindow", "RBBB"))
        self.label_17.setText(_translate("MainWindow", "Syn"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_4),
            _translate("MainWindow", "ECG Abnormalities"),
        )
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionDocumentation.setShortcut(_translate("MainWindow", "Ctrl+D"))


from pyqtgraph import PlotWidget
import images


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    with open("Diffnes.qss", "r") as f:
        stylesheet = f.read()
        app.setStyleSheet(stylesheet)

    equalizer = Equalizer(ui, file_path="")

    MainWindow.show()
    sys.exit(app.exec_())
